/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sohu_tv_bee_BeeVideoRender */

#ifndef _Included_com_sohu_tv_bee_BeeVideoRender
#define _Included_com_sohu_tv_bee_BeeVideoRender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sohu_tv_bee_BeeVideoRender
 * Method:    nativeCreateBeeVideoRenderer
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_sohu_tv_bee_BeeVideoRender_nativeCreateBeeVideoRenderer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_sohu_tv_bee_BeeVideoRender
 * Method:    nativeFreeBeeVideoRenderer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_sohu_tv_bee_BeeVideoRender_nativeFreeBeeVideoRenderer
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
