/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sohu_tv_bee_BeeSDK */

#ifndef _Included_com_sohu_tv_bee_BeeSDK
#define _Included_com_sohu_tv_bee_BeeSDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sohu_tv_bee_BeeSDK
 * Method:    nativeBeeSyncInit
 * Signature: (Landroid/content/Context;Lcom/sohu/tv/bee/BeeSystemParam;ILcom/sohu/tv/bee/BeeSDKSink;)I
 */
JNIEXPORT jint JNICALL Java_com_sohu_tv_bee_BeeSDK_nativeBeeSyncInit
  (JNIEnv *, jclass, jobject, jobject, jint, jobject);

/*
 * Class:     com_sohu_tv_bee_BeeSDK
 * Method:    nativeBeeSyncUninit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sohu_tv_bee_BeeSDK_nativeBeeSyncUninit
  (JNIEnv *, jclass);

/*
 * Class:     com_sohu_tv_bee_BeeSDK
 * Method:    nativeBeeSyncOpenSession
 * Signature: ()Lcom/sohu/tv/bee/BeeOpenSessionParam;
 */
JNIEXPORT jobject JNICALL Java_com_sohu_tv_bee_BeeSDK_nativeBeeSyncOpenSession
  (JNIEnv *, jclass);

/*
 * Class:     com_sohu_tv_bee_BeeSDK
 * Method:    nativeBeeSyncCloseSession
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_sohu_tv_bee_BeeSDK_nativeBeeSyncCloseSession
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_sohu_tv_bee_BeeSDK
 * Method:    nativeSetCodecEglContext
 * Signature: (Lorg/webrtc/EglBase/Context;Lorg/webrtc/EglBase/Context;)I
 */
JNIEXPORT jint JNICALL Java_com_sohu_tv_bee_BeeSDK_nativeSetCodecEglContext
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
