/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sohu_tv_bee_BeeSDKService */

#ifndef _Included_com_sohu_tv_bee_BeeSDKService
#define _Included_com_sohu_tv_bee_BeeSDKService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sohu_tv_bee_BeeSDKService
 * Method:    nativeCreateSDKService
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_sohu_tv_bee_BeeSDKService_nativeCreateSDKService
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_sohu_tv_bee_BeeSDKService
 * Method:    nativeFreeSDKService
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_sohu_tv_bee_BeeSDKService_nativeFreeSDKService
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_sohu_tv_bee_BeeSDKService
 * Method:    nativeReg
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_sohu_tv_bee_BeeSDKService_nativeReg
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_sohu_tv_bee_BeeSDKService
 * Method:    nativeUnReg
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_sohu_tv_bee_BeeSDKService_nativeUnReg
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_sohu_tv_bee_BeeSDKService
 * Method:    nativeExecute
 * Signature: (JLjava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_sohu_tv_bee_BeeSDKService_nativeExecute
  (JNIEnv *, jobject, jlong, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
